name: oura_health
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  android_intent_plus: ^6.0.0
  csv: ^6.0.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  health: ^13.1.4
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.1
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
