name: oura_health

environment:
  sdk: ^3.7.2

dependencies:
  android_intent_plus: ^5.3.0
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  health: ^12.1.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
